const { throwAppError, ERROR_CODE } = require('@app-core/errors');
const validator = require('@app-core/validator');
const CreatorCardRepository = require('@app/repository/creator-card');
const { CreatorCardMessages } = require('@app/messages');
const {
  ACTIVE_CARD_QUERY,
  CUSTOM_ERROR_CODES,
  createCardSpec,
  serializeCreatorCard,
  buildSlugBase,
  generateSlugSuffix,
} = require('./shared');

function throwValidationError(field, message) {
  throwAppError(message, 'SPCL_VALIDATION', {
    details: {
      [field]: message,
      __$app_first_message: message,
    },
  });
}

function validateRegexDrivenFields(serviceData, validatedData) {
  if (typeof serviceData.access_code !== 'undefined') {
    if (
      typeof serviceData.access_code !== 'string' ||
      !/^[A-Za-z0-9]{6}$/.test(serviceData.access_code.trim())
    ) {
      throwValidationError(
        'access_code',
        'Passed access_code value should match ^[A-Za-z0-9]{6}$'
      );
    }
  }

  if (
    typeof serviceData.slug !== 'undefined' &&
    (typeof serviceData.slug !== 'string' || !/^[A-Za-z0-9_-]+$/.test(serviceData.slug.trim()))
  ) {
    throwValidationError('slug', 'Passed slug value should match ^[A-Za-z0-9_-]+$');
  }

  if (Array.isArray(validatedData.links)) {
    validatedData.links.forEach((link, index) => {
      if (typeof link?.url !== 'string' || !/^https?:\/\/.+$/.test(link.url)) {
        throwValidationError(
          `links[${index}].url`,
          `Passed links[${index}].url value should match ^https?://.+$`
        );
      }
    });
  }
}

async function findActiveCardBySlug(slug) {
  return CreatorCardRepository.findOne({
    query: {
      slug,
      ...ACTIVE_CARD_QUERY,
    },
  });
}

async function assertSlugIsAvailable(slug) {
  const existingCard = await findActiveCardBySlug(slug);

  if (existingCard) {
    throwAppError(CreatorCardMessages.SLUG_TAKEN, CUSTOM_ERROR_CODES.SLUG_TAKEN);
  }
}

async function generateUniqueSlug(title) {
  const slugBase = buildSlugBase(title);

  if (slugBase.length >= 5) {
    const existingCard = await findActiveCardBySlug(slugBase);

    if (!existingCard) {
      return slugBase;
    }
  }

  // The retry path is intentionally sequential so each candidate slug can be checked
  // before generating the next one.
  /* eslint-disable no-await-in-loop */
  for (let attempt = 0; attempt < 5; attempt += 1) {
    const suffixedSlug = `${slugBase || 'card'}-${generateSlugSuffix()}`;
    const existingCard = await findActiveCardBySlug(suffixedSlug);

    if (!existingCard) {
      return suffixedSlug;
    }
  }
  /* eslint-enable no-await-in-loop */

  throwAppError(CreatorCardMessages.SLUG_GENERATION_FAILED, ERROR_CODE.APPERR);
}

async function persistCreatorCard(payload, options = {}) {
  const { isAutoGeneratedSlug = false } = options;
  let candidatePayload = { ...payload };

  // Duplicate-key retries must happen in order because each retry depends on the
  // slug chosen by the previous failed attempt.
  /* eslint-disable no-await-in-loop */
  for (let attempt = 0; attempt < 5; attempt += 1) {
    try {
      return await CreatorCardRepository.create(candidatePayload);
    } catch (error) {
      if (!(error.isApplicationError && error.errorCode === ERROR_CODE.DUPLRCRD)) {
        throw error;
      }

      if (!isAutoGeneratedSlug) {
        throwAppError(CreatorCardMessages.SLUG_TAKEN, CUSTOM_ERROR_CODES.SLUG_TAKEN);
      }

      candidatePayload = {
        ...candidatePayload,
        slug: await generateUniqueSlug(candidatePayload.title),
      };
    }
  }
  /* eslint-enable no-await-in-loop */

  throwAppError(CreatorCardMessages.SLUG_GENERATION_FAILED, ERROR_CODE.APPERR);
}

async function createCreatorCard(serviceData) {
  const validatedData = validator.validate(serviceData, createCardSpec);
  validateRegexDrivenFields(serviceData, validatedData);
  const hasAccessCode = typeof serviceData.access_code !== 'undefined';
  const accessCode = hasAccessCode ? serviceData.access_code.trim() : undefined;

  if (validatedData.access_type === 'private' && !accessCode) {
    throwAppError(
      CreatorCardMessages.ACCESS_CODE_REQUIRED,
      CUSTOM_ERROR_CODES.ACCESS_CODE_REQUIRED
    );
  }

  if ((!validatedData.access_type || validatedData.access_type === 'public') && hasAccessCode) {
    throwAppError(
      CreatorCardMessages.ACCESS_CODE_FORBIDDEN,
      CUSTOM_ERROR_CODES.ACCESS_CODE_FORBIDDEN
    );
  }

  const payload = {
    ...validatedData,
    access_type: validatedData.access_type || 'public',
  };
  const hasClientProvidedSlug = !!payload.slug;

  if (!hasClientProvidedSlug) {
    payload.slug = await generateUniqueSlug(payload.title);
  } else {
    await assertSlugIsAvailable(payload.slug);
  }

  payload.access_code = payload.access_type === 'private' ? accessCode : null;
  payload.deleted = null;

  try {
    const createdCard = await persistCreatorCard(payload, {
      isAutoGeneratedSlug: !hasClientProvidedSlug,
    });

    return {
      message: CreatorCardMessages.CREATION_SUCCESS,
      data: serializeCreatorCard(createdCard),
    };
  } catch (error) {
    if (
      error.isApplicationError &&
      (error.errorCode === ERROR_CODE.DUPLRCRD || error.errorCode === CUSTOM_ERROR_CODES.SLUG_TAKEN)
    ) {
      throwAppError(CreatorCardMessages.SLUG_TAKEN, CUSTOM_ERROR_CODES.SLUG_TAKEN);
    }

    throw error;
  }
}

module.exports = createCreatorCard;
